### ISSUE TITLE
DM-3212 Rescue

### ISSUE THREAD

**Issue by sebastienPoussard** [joelsernamoreno/badusb_sd_wifi#5]
Greetings,

I did some wrong manipulations on  my DM-3212. 
When i plug  the badusb, my os (Debian) doesn't recognize it through lsusb command.
No information in the kernel neither (dmesg command)

But when i press the reset button and quickly type lsusb, the system recognize it.
in the kernel i see the following : 

```
usb 1-2: new full-speed USB device number 102 using xhci_hcd  
usb 1-2: New USB device found, idVendor=2341, idProduct=0036, bcdDevice= 0.01                                        
usb 1-2: New USB device strings: Mfr=2, Product=1, SerialNumber=0  
usb 1-2: Product: Arduino Leonardo  
usb 1-2: Manufacturer: Arduino LLC  
cdc_acm 1-2:1.0: ttyACM0: USB ACM device  
usb 1-2: USB disconnect, device number 102  
```

sometimes (but not always) followed with 
```
xhci_hcd 0000:00:14.0: WARN Cannot submit Set TR Deq Ptr  
xhci_hcd 0000:00:14.0: A Set TR Deq Ptr command is pending.  
xhci_hcd 0000:00:14.0: WARN Set TR Deq Ptr cmd failed due to incorrect slot or ep state.
```

Arduido IDE detect for a short moment the port.
The device quickly go off and I doesn't have the time to do anything.
(Device seems to be powered on for approximately 8sec with the red LED blinking)

I Suspect that i pushed some code in the wrong memory place, maybe I destroyed the firmware or the bios ?
Unfortunately i just started messing with this kind of hardware and my knowledge is limited in this area, i would greatly appreciate any advice.
any ideas ?

Best regards.

**Comment by joelsernamoreno** [comment]
Try fixing the device with this:

1.- Connect the device without the jumper (your PC doesn't have to recognize the device)

2.- Open Arduino IDE

3.- Open the scketch Blink (basic sketch)

4.- Tools -> Board: Arduino Leonardo

5.- Upload sketch button

6.- When the Arduino IDE looked for the ttyACMX or ttyUSBX ports, press the reset button on the device

Thanks!
